config/routes.rb
Rails.application.routes.draw do

	resources :links
  root to: "links#index"
end

app/models/link.rb
class Link < ActiveRecord::Base
	validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
  	@links = Link.all
  end

  def show
  end

  def new
  	@link = Link.new
  end

  def create
  	@link = Link.new(link_params)

  	if @link.save
  		flash[:notice] = "Created link successfully."
  		redirect_to @link
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
    if @link.update(link_params)
      flash[:notice] = "Updated link successfully."
      redirect_to @link
    else
      render "edit"
    end
  end

  def destroy
    @link.destroy
    
    flash[:notice] = "Link deleted successfully."
    redirect_to links_path
  end

  private

    def set_link
    	@link = Link.find(params[:id])
    end

    def link_params
    	params.require(:link).permit(:title, :url)
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redditapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
	  <%= yield %>
	</div>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
	
	<div class="form-group">
	  <%= f.label :title %>
	  <%= f.text_field :title, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :url %>
		<%= f.text_field :url, class: "form-control"  %>
	</div>

	<div class="form-group">
	  <%= f.submit class: "btn btn-primary" %>
	</div>
<% end %>

app/views/links/edit.html.erb
<p>
	<%= link_to "<< Go back", links_path %>
</p>

<h1>Editing link</h1>

<%= render "form" %>

app/views/links/index.html.erb
<h1>All Links</h1>

<p>
	<%= link_to "Add a link", new_link_path, class: "btn btn-primary" %>	
</p>

<table class="table">
	<thead>
		<th>Title</th>
		<th>Action</th>
	</thead>

	<tbody>
		<% @links.each do |link| %>
			<tr>
				<td>		
				  <%= link_to link.title, link_path(link) %>
				</td>
				<td>
					<%= link_to "Show", link %>
					<%= link_to "Edit", edit_link_path(link) %>
					<%= link_to "Delete", link, method: :delete, data: { confirm: "Are your sure?"} %>
				</td>
			</tr>			
		<% end %>	
	</tbody>
</table>

app/views/links/new.html.erb
<p>
	<%= link_to "<< Go back", links_path %>
</p>

<h1>Add new link</h1>

<%= render "form" %>

app/views/links/show.html.erb
<p>
	<%= link_to "<< Go back", links_path %>
</p>

<p>
	<%= @link.title %>
</p>

<p>
	<%= @link.url %>
</p>